openconnectivityfoundation/security

- json-schemas/oic.sec.cred.json
Currently oic.sec.cred.json is not a valid json because of additional coma in line 34
> Remove coma after last property in oic.sec.cred

- json-schemas/oic.core.json
- json-schemas/oic.oic-link-schema.json
- json-schemas/oic.r.doxm.json
- json-schemas/oic.r.pstat.json
This change is to make the readOnly properties machine readable in
compliance with the JSON-hyper schema readOnly definition. See:
http://json-schema.org/latest/json-schema-hypermedia.html#anchor15
> Add readOnly property where appropriate in the json schema's.

- schemas/oic.oic-link-schema.json
- schemas/oic.r.acl.json
- schemas/oic.r.amacl.json
- schemas/oic.r.cred.json
- schemas/oic.r.doxm.json
- schemas/oic.r.pstat.json
- schemas/oic.r.sacl.json
- schemas/oic.sec.ace.json
- schemas/oic.sec.cred.json
- schemas/oic.sec.didtype.json
The format=uuid doesn't validate in  ATOM with apiworkbench plugin from RAML.
In the core we replaced those occurrences with an OIC defined thype using string and pattern.   
See https://github.com/stephanesan/core/blob/master/schemas/oic.types-schema.json
The proposal here is to replace those failing "format=uuid" occurrences with the uuid type already defined in the ocf core types.
This will allow the validator to proceed past this error to validate the remaining code.
> JSON Schema validation v4 spec doesn't recognize format=uuid.

- oic.r.acl.raml
Fix example to match the time-interval schema definition.
Add missing idt property.
> Fix example in acl.raml.

- schemas/oic.r.acl.json
- schemas/oic.r.amacl.json
- schemas/oic.r.cred.json
- schemas/oic.r.doxm.json
- schemas/oic.r.pstat.json
- schemas/oic.r.sacl.json
- schemas/oic.r.svc.json
- schemas/oic.sec.svctype.json
Using references to definitions works properly in ATOM and gets rid of the useless allOf anyway. 
In short, this hack solves the ATOM api-workbench limitation and but at the same time cleans up the schema design!
> Fix svctype ref

- schemas/oic.r.acl.json
- schemas/oic.r.sacl.json
- schemas/oic.sec.ace.json
- schemas/oic.sec.cred.json
- schemas/oic.sec.roletype.json
Using references to definitions works properly in ATOM and gets rid of the useless allOf anyway.
In short, this hack solves the ATOM api-workbench limitation and but at the same time cleans up the schema design!
> Fix acl ref

- schemas/oic.sec.svc.json
The pattern in the other files seem to indicate that the bitmask
property is never directly included but rather used as a type
definition reference. So the schema is modified to comply with this
design pattern.
> Fix the schema to fit the example in svc.raml.

- schemas/oic.r.doxm.json
- schemas/oic.r.pstat.json
Since the property tag has been introduced, the ReadOnly string in the description is no longer necessary.
> Removed "ReadOnly" from description fields for ReadOnly properties

- oic.r.acl.raml
- oic.r.acl2.raml
- oic.r.amacl.raml
- oic.r.cred.raml
- oic.r.crl.raml
- oic.r.doxm.raml
- oic.r.pstat.raml
- oic.r.sacl.raml
- oic.r.svc.raml
OCF 1.0 Security uses well-known URIs for its resources. This change replaces the long-existing placeholder URIs in the RAML files with the well-known URI paths.
> Replace the placeholder URI path declarations with well-known paths

- examples/oic.sec.roletype-example.json
- oic.r.cred.raml
- schemas/oic.sec.roletype.json
oic.sec.roletype does not agree with the security WG spec; change
"roles" array to be a "role" single string as described, and only
mark "role" as a required field.
> Make oic.sec.roletype consistent with spec'd definition

- schemas/oic.sec.dpmtype.json
Added Software Update bits to oic.sec.dpmtype
(the branch was defined many moons ago, but forgot to create the PR for it)
> Changes for OCF 1.0 CR-24: Software update support

- oic.r.acl2.raml
- schemas/oic.r.acl2.json
There will be a corresponding spec change for the rename.
This merging of the PR can be coordinated with the spec change.
> Renamed the top-level ACL2 list to "aclist2" as discussed/requested by NathanH-S

- schemas/oic.r.csr.json
As length field to indicate the length of the csr, as default is only 64 bytes.
> Bug1811: Add length to the csr string

- schemas/oic.sec.dpmtype.json
oic.sec.bss was removed from the security specification. Removing bss from the spec.
Signed-off-by: Habib Virji <habib.virji@samsung.com>
> [Bug1766] oic.sec.bss removal

- schemas/oic.sec.ace2.json
WC property updated to be only string type.
Signed-off-by: Habib Virji <habib.virji@samsung.com>
> oic.sec.ace2 wc property schema update

- schemas/oic.r.acl2-Update.json
- schemas/oic.r.cred-Update.json
Update schemas did not need required property.
Signed-off-by: Habib Virji <habib.virji@samsung.com>
> Update schemas required property removal

- schemas/oic.sec.cred-base.json
CR 2390 resolves security vulnerability for cases when certificate credentials are used to verify identity in secure D2D connections.
To support legacy deployments and for CTT use, wildcard support should be used.
In future deployments, wildcard use is discouraged.
> CR 2390: Escalation

- schemas/oic.r.csr.json
-Update schema to mark "csr" & "encoding" properties as read only.
Signed-off-by: Ankur Bansal <ankur.b1@samsung.com>
> oic.r.csr: Fix readOnly attribute for properties

- swagger2.0/oic.sec.cred.swagger.json
- swagger2.0/oic.sec.csr.swagger.json
Due to lack of support in spec, DER encoding is removed
> Remove DER encoding

- swagger2.0/oic.sec.acl2.swagger.json
Resource Type and Interface matching is under-specified in the spec.
Since there is little value seen in these kind of access control policies, rather then improving the definition, we can deprecate the feature.
> Deprecating "rt" and "if" matching ACEs

- swagger2.0/oic.sec.acl2.swagger.json
- swagger2.0/oic.sec.cred.swagger.json
- swagger2.0/oic.sec.csr.swagger.json
- swagger2.0/oic.sec.doxm.swagger.json
- swagger2.0/oic.sec.pstat.swagger.json
- swagger2.0/oic.sec.roles.swagger.json
- swagger2.0/oic.sec.sp.swagger.json
It is recommended to avoid using "oic.if.baseline". Support of at least one other interface is needed.
> [Bug 3101] Adding "oic.if.rw" to all SVRs
